modLoader="javafml"
loaderVersion="[49,)"
license="MIT"
issueTrackerURL="https://github.com/AgriCraft/AgriCraft/issues/"

[[mods]]
modId="agricraft"
version="${version}"
displayName="AgriCraft"
displayURL="https://www.curseforge.com/minecraft/mc-mods/agricraft"
updateJSONURL = "https://raw.githubusercontent.com/AgriCraft/AgriCraft/master/version.json"
logoFile="logo.png"
authors="InfinityRaider, Ketheroth"
description='''
Agricultural farming extended
'''

[[dependencies.agricraft]]
modId="forge"
mandatory=true
versionRange="[49,)"
ordering="NONE"
side="BOTH"

[[dependencies.agricraft]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.agricraft]]
modId = "resourcefulconfig"
mandatory = true
versionRange = "[2.4.2,)"
ordering = "NONE"
side = "BOTH"
